/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	� by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.jhotdraw.test.standard

import java.awt.Point
import junit.framework.TestCase
import org.jhotdraw.figures.RectangleFigure
import org.jhotdraw.standard.SingleFigureEnumerator

// JUnitDoclet end import
/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/
// JUnitDoclet begin javadoc_class
/**
 * TestCase SingleFigureEnumeratorTest is generated by
 * JUnitDoclet to hold the tests for SingleFigureEnumerator.
 * @see org.jhotdraw.standard.SingleFigureEnumerator
 */
class SingleFigureEnumeratorTest(name: String) extends TestCase(name) {

  /**
   * Factory method for instances of the class to be tested.
   */
  def createInstance: SingleFigureEnumerator = {
    return new SingleFigureEnumerator(new RectangleFigure(new Point(10, 10), new Point(100, 100)))
  }

  /**
   * Method setUp is overwriting the framework method to
   * prepare an instance of this TestCase for a single test.
   * It's called from the JUnit framework only.
   */
  override protected def setUp {
    super.setUp
    singlefigureenumerator = createInstance
  }

  /**
   * Method tearDown is overwriting the framework method to
   * clean up after each single test of this TestCase.
   * It's called from the JUnit framework only.
   */
  override protected def tearDown {
    singlefigureenumerator = null
    super.tearDown
  }

  /**
   * Method testHasNextFigure is testing hasNextFigure
   * @see org.jhotdraw.standard.SingleFigureEnumerator#hasNextFigure()
   */
  def testHasNextFigure {
  }

  /**
   * Method testNextFigure is testing nextFigure
   * @see org.jhotdraw.standard.SingleFigureEnumerator#nextFigure()
   */
  def testNextFigure {
  }

  /**
   * Method testReset is testing reset
   * @see org.jhotdraw.standard.SingleFigureEnumerator#reset()
   */
  def testReset {
  }

  /**
   * JUnitDoclet moves marker to this method, if there is not match
   * for them in the regenerated code and if the marker is not empty.
   * This way, no test gets lost when regenerating after renaming.
   * <b>Method testVault is supposed to be empty.</b>
   */
  def testVault {
  }

  private var singlefigureenumerator: SingleFigureEnumerator = null
}

