/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	� by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.shotdraw.test.util

import org.shotdraw.util.Clipboard
import junit.framework.TestCase

// JUnitDoclet begin import
// JUnitDoclet end import
/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/
// JUnitDoclet begin javadoc_class
/**
 * TestCase ClipboardTest is generated by
 * JUnitDoclet to hold the tests for Clipboard.
 * @see org.shotdraw.util.Clipboard
 */
class ClipboardTest(name: String) extends TestCase(name) {

  /**
   * Factory method for instances of the class to be tested.
   */
  def createInstance: Clipboard = {
    Clipboard.getClipboard
  }

  /**
   * Method setUp is overwriting the framework method to
   * prepare an instance of this TestCase for a single test.
   * It's called from the JUnit framework only.
   */
  override protected def setUp {
    super.setUp
    clipboard = createInstance
  }

  /**
   * Method tearDown is overwriting the framework method to
   * clean up after each single test of this TestCase.
   * It's called from the JUnit framework only.
   */
  override protected def tearDown {
    clipboard = null
    super.tearDown
  }

  /**
   * Method testGetClipboard is testing getClipboard
   * @see org.shotdraw.util.Clipboard#getClipboard()
   */
  def testGetClipboard {
  }

  /**
   * Method testSetGetContents is testing setContents
   * and getContents together by setting some value
   * and verifying it by reading.
   * @see org.shotdraw.util.Clipboard#setContents(java.lang.Object)
   * @see org.shotdraw.util.Clipboard#getContents()
   */
  def testSetGetContents {
    val tests: List[AnyRef] = List(new AnyRef, null)
    tests foreach {e =>
      clipboard.setContents(e)
      assert(e == clipboard.getContents)
    }
  }

  /**
   * JUnitDoclet moves marker to this method, if there is not match
   * for them in the regenerated code and if the marker is not empty.
   * This way, no test gets lost when regenerating after renaming.
   * <b>Method testVault is supposed to be empty.</b>
   */
  def testVault {
  }

  private var clipboard: Clipboard = null
}

