/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	� by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.shotdraw.test.standard

import org.shotdraw.standard.ChopBoxConnector
import junit.framework.TestCase

// JUnitDoclet begin import
// JUnitDoclet end import
/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/
// JUnitDoclet begin javadoc_class
/**
 * TestCase ChopBoxConnectorTest is generated by
 * JUnitDoclet to hold the tests for ChopBoxConnector.
 * @see org.shotdraw.standard.ChopBoxConnector
 */
class ChopBoxConnectorTest(name: String) extends TestCase(name) {

  /**
   * Factory method for instances of the class to be tested.
   */
  def createInstance: ChopBoxConnector = {
    new ChopBoxConnector
  }

  /**
   * Method setUp is overwriting the framework method to
   * prepare an instance of this TestCase for a single test.
   * It's called from the JUnit framework only.
   */
  override protected def setUp {
    super.setUp
    chopboxconnector = createInstance
  }

  /**
   * Method tearDown is overwriting the framework method to
   * clean up after each single test of this TestCase.
   * It's called from the JUnit framework only.
   */
  override protected def tearDown {
    chopboxconnector = null
    super.tearDown
  }

  /**
   * Method testFindStart is testing findStart
   * @see org.shotdraw.standard.ChopBoxConnector#findStart(org.shotdraw.framework.ConnectionFigure)
   */
  def testFindStart {
  }

  /**
   * Method testFindEnd is testing findEnd
   * @see org.shotdraw.standard.ChopBoxConnector#findEnd(org.shotdraw.framework.ConnectionFigure)
   */
  def testFindEnd {
  }

  /**
   * JUnitDoclet moves marker to this method, if there is not match
   * for them in the regenerated code and if the marker is not empty.
   * This way, no test gets lost when regenerating after renaming.
   * <b>Method testVault is supposed to be empty.</b>
   */
  def testVault {
  }

  private var chopboxconnector: ChopBoxConnector = null
}

