/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	� by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.shotdraw.test.standard

import org.shotdraw.standard.OffsetLocator
import junit.framework.TestCase

// JUnitDoclet begin import
// JUnitDoclet end import
/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/
// JUnitDoclet begin javadoc_class
/**
 * TestCase OffsetLocatorTest is generated by
 * JUnitDoclet to hold the tests for OffsetLocator.
 * @see org.shotdraw.standard.OffsetLocator
 */
class OffsetLocatorTest(name: String) extends TestCase(name) {

  /**
   * Factory method for instances of the class to be tested.
   */
  def createInstance: OffsetLocator = {
    new OffsetLocator
  }

  /**
   * Method setUp is overwriting the framework method to
   * prepare an instance of this TestCase for a single test.
   * It's called from the JUnit framework only.
   */
  override protected def setUp {
    super.setUp
    offsetlocator = createInstance
  }

  /**
   * Method tearDown is overwriting the framework method to
   * clean up after each single test of this TestCase.
   * It's called from the JUnit framework only.
   */
  override protected def tearDown {
    offsetlocator = null
    super.tearDown
  }

  /**
   * Method testLocate is testing locate
   * @see org.shotdraw.standard.OffsetLocator#locate(org.shotdraw.framework.Figure)
   */
  def testLocate {
  }

  /**
   * Method testMoveBy is testing moveBy
   * @see org.shotdraw.standard.OffsetLocator#moveBy(int, int)
   */
  def testMoveBy {
  }

  /**
   * Method testWrite is testing write
   * @see org.shotdraw.standard.OffsetLocator#write(org.shotdraw.util.StorableOutput)
   */
  def testWrite {
  }

  /**
   * Method testRead is testing read
   * @see org.shotdraw.standard.OffsetLocator#read(org.shotdraw.util.StorableInput)
   */
  def testRead {
  }

  /**
   * JUnitDoclet moves marker to this method, if there is not match
   * for them in the regenerated code and if the marker is not empty.
   * This way, no test gets lost when regenerating after renaming.
   * <b>Method testVault is supposed to be empty.</b>
   */
  def testVault {
  }

  private var offsetlocator: OffsetLocator = null
}

