/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	� by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.jhotdraw.test.standard

import java.awt.Point
import junit.framework.TestCase
import org.jhotdraw.figures.RectangleFigure
import org.jhotdraw.standard.NullHandle
import org.jhotdraw.standard.RelativeLocator

// JUnitDoclet end import
/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/
// JUnitDoclet begin javadoc_class
/**
 * TestCase NullHandleTest is generated by
 * JUnitDoclet to hold the tests for NullHandle.
 * @see org.jhotdraw.standard.NullHandle
 */
class NullHandleTest(name: String) extends TestCase(name) {

  /**
   * Factory method for instances of the class to be tested.
   */
  def createInstance: NullHandle = {
    new NullHandle(new RectangleFigure(new Point(5, 5), new Point(100, 100)), new RelativeLocator)
  }

  /**
   * Method setUp is overwriting the framework method to
   * prepare an instance of this TestCase for a single test.
   * It's called from the JUnit framework only.
   */
  override protected def setUp {
    super.setUp
    nullhandle = createInstance
  }

  /**
   * Method tearDown is overwriting the framework method to
   * clean up after each single test of this TestCase.
   * It's called from the JUnit framework only.
   */
  override protected def tearDown {
    nullhandle = null
    super.tearDown
  }

  /**
   * Method testDraw is testing draw
   * @see org.jhotdraw.standard.NullHandle#draw(java.awt.Graphics)
   */
  def testDraw {
  }

  /**
   * JUnitDoclet moves marker to this method, if there is not match
   * for them in the regenerated code and if the marker is not empty.
   * This way, no test gets lost when regenerating after renaming.
   * <b>Method testVault is supposed to be empty.</b>
   */
  def testVault {
  }

  private var nullhandle: NullHandle = null
}

