/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	� by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.shotdraw.test.framework

import java.awt.Rectangle
import junit.framework.TestCase
import org.shotdraw.framework.DrawingChangeEvent
import org.shotdraw.standard.StandardDrawing

// JUnitDoclet end import
/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/
// JUnitDoclet begin javadoc_class
/**
 * TestCase DrawingChangeEventTest is generated by
 * JUnitDoclet to hold the tests for DrawingChangeEvent.
 * @see org.shotdraw.framework.DrawingChangeEvent
 */
class DrawingChangeEventTest(name: String) extends TestCase(name) {

  /**
   * Factory method for instances of the class to be tested.
   */
  def createInstance: DrawingChangeEvent = {
    new DrawingChangeEvent(new StandardDrawing, new Rectangle(10, 10, 100, 100))
  }

  /**
   * Method setUp is overwriting the framework method to
   * prepare an instance of this TestCase for a single test.
   * It's called from the JUnit framework only.
   */
  override protected def setUp() {
    super.setUp
    drawingchangeevent = createInstance
  }

  /**
   * Method tearDown is overwriting the framework method to
   * clean up after each single test of this TestCase.
   * It's called from the JUnit framework only.
   */
  override protected def tearDown() {
    drawingchangeevent = null
    super.tearDown
  }

  /**
   * Method testGetDrawing is testing getDrawing
   * @see org.shotdraw.framework.DrawingChangeEvent#getDrawing()
   */
  def testGetDrawing() {
  }

  /**
   * Method testGetInvalidatedRectangle is testing getInvalidatedRectangle
   * @see org.shotdraw.framework.DrawingChangeEvent#getInvalidatedRectangle()
   */
  def testGetInvalidatedRectangle() {
  }

  /**
   * JUnitDoclet moves marker to this method, if there is not match
   * for them in the regenerated code and if the marker is not empty.
   * This way, no test gets lost when regenerating after renaming.
   * <b>Method testVault is supposed to be empty.</b>
   */
  def testVault() {
  }

  private var drawingchangeevent: DrawingChangeEvent = null
}

