/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	� by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.shotdraw.test.figures

import org.shotdraw.figures.EllipseFigure
import junit.framework.TestCase

// JUnitDoclet begin import
// JUnitDoclet end import
/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/
// JUnitDoclet begin javadoc_class
/**
 * TestCase EllipseFigureTest is generated by
 * JUnitDoclet to hold the tests for EllipseFigure.
 * @see org.shotdraw.figures.EllipseFigure
 */
class EllipseFigureTest(name: String) extends TestCase(name) {

  /**
   * Factory method for instances of the class to be tested.
   */
  def createInstance: EllipseFigure = {
    new EllipseFigure
  }

  /**
   * Method setUp is overwriting the framework method to
   * prepare an instance of this TestCase for a single test.
   * It's called from the JUnit framework only.
   */
  override protected def setUp {
    super.setUp
    ellipsefigure = createInstance
  }

  /**
   * Method tearDown is overwriting the framework method to
   * clean up after each single test of this TestCase.
   * It's called from the JUnit framework only.
   */
  override protected def tearDown {
    ellipsefigure = null
    super.tearDown
  }

  /**
   * Method testHandles is testing handles
   * @see org.shotdraw.figures.EllipseFigure#handles()
   */
  def testHandles {
  }

  /**
   * Method testBasicDisplayBox is testing basicDisplayBox
   * @see org.shotdraw.figures.EllipseFigure#basicDisplayBox(java.awt.Point, java.awt.Point)
   */
  def testBasicDisplayBox {
  }

  /**
   * Method testDisplayBox is testing displayBox
   * @see org.shotdraw.figures.EllipseFigure#displayBox()
   */
  def testDisplayBox {
  }

  /**
   * Method testDrawBackground is testing drawBackground
   * @see org.shotdraw.figures.EllipseFigure#drawBackground(java.awt.Graphics)
   */
  def testDrawBackground {
  }

  /**
   * Method testDrawFrame is testing drawFrame
   * @see org.shotdraw.figures.EllipseFigure#drawFrame(java.awt.Graphics)
   */
  def testDrawFrame {
  }

  /**
   * Method testConnectionInsets is testing connectionInsets
   * @see org.shotdraw.figures.EllipseFigure#connectionInsets()
   */
  def testConnectionInsets {
  }

  /**
   * Method testConnectorAt is testing connectorAt
   * @see org.shotdraw.figures.EllipseFigure#connectorAt(int, int)
   */
  def testConnectorAt {
  }

  /**
   * Method testWrite is testing write
   * @see org.shotdraw.figures.EllipseFigure#write(org.shotdraw.util.StorableOutput)
   */
  def testWrite {
  }

  /**
   * Method testRead is testing read
   * @see org.shotdraw.figures.EllipseFigure#read(org.shotdraw.util.StorableInput)
   */
  def testRead {
  }

  /**
   * JUnitDoclet moves marker to this method, if there is not match
   * for them in the regenerated code and if the marker is not empty.
   * This way, no test gets lost when regenerating after renaming.
   * <b>Method testVault is supposed to be empty.</b>
   */
  def testVault {
  }

  private var ellipsefigure: EllipseFigure = null
}

