/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	� by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.shotdraw.test.figures

import org.shotdraw.figures.GroupFigure
import junit.framework.TestCase

// JUnitDoclet begin import
// JUnitDoclet end import
/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/
// JUnitDoclet begin javadoc_class
/**
 * TestCase GroupFigureTest is generated by
 * JUnitDoclet to hold the tests for GroupFigure.
 * @see org.shotdraw.figures.GroupFigure
 */
class GroupFigureTest(name: String) extends TestCase(name) {

  /**
   * Factory method for instances of the class to be tested.
   */
  def createInstance: GroupFigure = {
    new GroupFigure
  }

  /**
   * Method setUp is overwriting the framework method to
   * prepare an instance of this TestCase for a single test.
   * It's called from the JUnit framework only.
   */
  override protected def setUp {
    super.setUp
    groupfigure = createInstance
  }

  /**
   * Method tearDown is overwriting the framework method to
   * clean up after each single test of this TestCase.
   * It's called from the JUnit framework only.
   */
  override protected def tearDown {
    groupfigure = null
    super.tearDown
  }

  /**
   * Method testCanConnect is testing canConnect
   * @see org.shotdraw.figures.GroupFigure#canConnect()
   */
  def testCanConnect {
  }

  /**
   * Method testDisplayBox is testing displayBox
   * @see org.shotdraw.figures.GroupFigure#displayBox()
   */
  def testDisplayBox {
  }

  /**
   * Method testBasicDisplayBox is testing basicDisplayBox
   * @see org.shotdraw.figures.GroupFigure#basicDisplayBox(java.awt.Point, java.awt.Point)
   */
  def testBasicDisplayBox {
  }

  /**
   * Method testDecompose is testing decompose
   * @see org.shotdraw.figures.GroupFigure#decompose()
   */
  def testDecompose {
  }

  /**
   * Method testHandles is testing handles
   * @see org.shotdraw.figures.GroupFigure#handles()
   */
  def testHandles {
  }

  /**
   * Method testSetAttribute is testing setAttribute
   * @see org.shotdraw.figures.GroupFigure#setAttribute(java.lang.String, java.lang.Object)
   */
  def testSetAttribute {
  }

  /**
   * JUnitDoclet moves marker to this method, if there is not match
   * for them in the regenerated code and if the marker is not empty.
   * This way, no test gets lost when regenerating after renaming.
   * <b>Method testVault is supposed to be empty.</b>
   */
  def testVault {
  }

  private var groupfigure: GroupFigure = null
}

