/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	� by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.shotdraw.test.figures

import org.shotdraw.figures.LineFigure
import junit.framework.TestCase

// JUnitDoclet begin import
// JUnitDoclet end import
/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/
// JUnitDoclet begin javadoc_class
/**
 * TestCase LineFigureTest is generated by
 * JUnitDoclet to hold the tests for LineFigure.
 * @see org.shotdraw.figures.LineFigure
 */
class LineFigureTest(name: String) extends TestCase(name) {

  /**
   * Factory method for instances of the class to be tested.
   */
  def createInstance: LineFigure = {
    new LineFigure
  }

  /**
   * Method setUp is overwriting the framework method to
   * prepare an instance of this TestCase for a single test.
   * It's called from the JUnit framework only.
   */
  override protected def setUp() {
    super.setUp
    linefigure = createInstance
  }

  /**
   * Method tearDown is overwriting the framework method to
   * clean up after each single test of this TestCase.
   * It's called from the JUnit framework only.
   */
  override protected def tearDown() {
    linefigure = null
    super.tearDown
  }

  /**
   * Method testStartPoint is testing startPoint
   * @see org.shotdraw.figures.LineFigure#startPoint()
   */
  def testStartPoint() {
  }

  /**
   * Method testEndPoint is testing endPoint
   * @see org.shotdraw.figures.LineFigure#endPoint()
   */
  def testEndPoint() {
  }

  /**
   * Method testSetPoints is testing setPoints
   * @see org.shotdraw.figures.LineFigure#setPoints(java.awt.Point, java.awt.Point)
   */
  def testSetPoints() {
  }

  /**
   * Method testBasicDisplayBox is testing basicDisplayBox
   * @see org.shotdraw.figures.LineFigure#basicDisplayBox(java.awt.Point, java.awt.Point)
   */
  def testBasicDisplayBox() {
  }

  /**
   * JUnitDoclet moves marker to this method, if there is not match
   * for them in the regenerated code and if the marker is not empty.
   * This way, no test gets lost when regenerating after renaming.
   * <b>Method testVault is supposed to be empty.</b>
   */
  def testVault() {
  }

  private var linefigure: LineFigure = null
}

