/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	� by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.jhotdraw.test.figures

import org.jhotdraw.figures.LineConnection
import junit.framework.TestCase

// JUnitDoclet begin import
// JUnitDoclet end import
/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/
// JUnitDoclet begin javadoc_class
/**
 * TestCase LineConnectionTest is generated by
 * JUnitDoclet to hold the tests for LineConnection.
 * @see org.jhotdraw.figures.LineConnection
 */
class LineConnectionTest(name: String) extends TestCase(name) {

  /**
   * Factory method for instances of the class to be tested.
   */
  def createInstance: LineConnection = {
    new LineConnection
  }

  /**
   * Method setUp is overwriting the framework method to
   * prepare an instance of this TestCase for a single test.
   * It's called from the JUnit framework only.
   */
  override protected def setUp {
    super.setUp
    lineconnection = createInstance
  }

  /**
   * Method tearDown is overwriting the framework method to
   * clean up after each single test of this TestCase.
   * It's called from the JUnit framework only.
   */
  override protected def tearDown {
    lineconnection = null
    super.tearDown
  }

  /**
   * Method testCanConnect is testing canConnect
   * @see org.jhotdraw.figures.LineConnection#canConnect()
   */
  def testCanConnect {
  }

  /**
   * Method testConnectStart is testing connectStart
   * @see org.jhotdraw.figures.LineConnection#connectStart(org.jhotdraw.framework.Connector)
   */
  def testConnectStart {
  }

  /**
   * Method testConnectEnd is testing connectEnd
   * @see org.jhotdraw.figures.LineConnection#connectEnd(org.jhotdraw.framework.Connector)
   */
  def testConnectEnd {
  }

  /**
   * Method testDisconnectStart is testing disconnectStart
   * @see org.jhotdraw.figures.LineConnection#disconnectStart()
   */
  def testDisconnectStart {
  }

  /**
   * Method testDisconnectEnd is testing disconnectEnd
   * @see org.jhotdraw.figures.LineConnection#disconnectEnd()
   */
  def testDisconnectEnd {
  }

  /**
   * Method testConnectsSame is testing connectsSame
   * @see org.jhotdraw.figures.LineConnection#connectsSame(org.jhotdraw.framework.ConnectionFigure)
   */
  def testConnectsSame {
  }

  /**
   * Method testStartFigure is testing startFigure
   * @see org.jhotdraw.figures.LineConnection#startFigure()
   */
  def testStartFigure {
  }

  /**
   * Method testEndFigure is testing endFigure
   * @see org.jhotdraw.figures.LineConnection#endFigure()
   */
  def testEndFigure {
  }

  /**
   * Method testGetStartConnector is testing getStartConnector
   * @see org.jhotdraw.figures.LineConnection#getStartConnector()
   */
  def testGetStartConnector {
  }

  /**
   * Method testGetEndConnector is testing getEndConnector
   * @see org.jhotdraw.figures.LineConnection#getEndConnector()
   */
  def testGetEndConnector {
  }

  /**
   * Method testStartPoint is testing startPoint
   * @see org.jhotdraw.figures.LineConnection#startPoint(int, int)
   */
  def testStartPoint {
  }

  /**
   * Method testEndPoint is testing endPoint
   * @see org.jhotdraw.figures.LineConnection#endPoint(int, int)
   */
  def testEndPoint {
  }

  /**
   * Method testHandles is testing handles
   * @see org.jhotdraw.figures.LineConnection#handles()
   */
  def testHandles {
  }

  /**
   * Method testSetPointAt is testing setPointAt
   * @see org.jhotdraw.figures.LineConnection#setPointAt(java.awt.Point, int)
   */
  def testSetPointAt {
  }

  /**
   * Method testInsertPointAt is testing insertPointAt
   * @see org.jhotdraw.figures.LineConnection#insertPointAt(java.awt.Point, int)
   */
  def testInsertPointAt {
  }

  /**
   * Method testRemovePointAt is testing removePointAt
   * @see org.jhotdraw.figures.LineConnection#removePointAt(int)
   */
  def testRemovePointAt {
  }

  /**
   * Method testUpdateConnection is testing updateConnection
   * @see org.jhotdraw.figures.LineConnection#updateConnection()
   */
  def testUpdateConnection {
  }

  /**
   * Method testLayoutConnection is testing layoutConnection
   * @see org.jhotdraw.figures.LineConnection#layoutConnection()
   */
  def testLayoutConnection {
  }

  /**
   * Method testFigureChanged is testing figureChanged
   * @see org.jhotdraw.figures.LineConnection#figureChanged(org.jhotdraw.framework.FigureChangeEvent)
   */
  def testFigureChanged {
  }

  /**
   * Method testFigureRemoved is testing figureRemoved
   * @see org.jhotdraw.figures.LineConnection#figureRemoved(org.jhotdraw.framework.FigureChangeEvent)
   */
  def testFigureRemoved {
  }

  /**
   * Method testFigureRequestRemove is testing figureRequestRemove
   * @see org.jhotdraw.figures.LineConnection#figureRequestRemove(org.jhotdraw.framework.FigureChangeEvent)
   */
  def testFigureRequestRemove {
  }

  /**
   * Method testFigureInvalidated is testing figureInvalidated
   * @see org.jhotdraw.figures.LineConnection#figureInvalidated(org.jhotdraw.framework.FigureChangeEvent)
   */
  def testFigureInvalidated {
  }

  /**
   * Method testFigureRequestUpdate is testing figureRequestUpdate
   * @see org.jhotdraw.figures.LineConnection#figureRequestUpdate(org.jhotdraw.framework.FigureChangeEvent)
   */
  def testFigureRequestUpdate {
  }

  /**
   * Method testRelease is testing release
   * @see org.jhotdraw.figures.LineConnection#release()
   */
  def testRelease {
  }

  /**
   * Method testWrite is testing write
   * @see org.jhotdraw.figures.LineConnection#write(org.jhotdraw.util.StorableOutput)
   */
  def testWrite {
  }

  /**
   * Method testRead is testing read
   * @see org.jhotdraw.figures.LineConnection#read(org.jhotdraw.util.StorableInput)
   */
  def testRead {
  }

  /**
   * Method testVisit is testing visit
   * @see org.jhotdraw.figures.LineConnection#visit(org.jhotdraw.framework.FigureVisitor)
   */
  def testVisit {
  }

  /**
   * JUnitDoclet moves marker to this method, if there is not match
   * for them in the regenerated code and if the marker is not empty.
   * This way, no test gets lost when regenerating after renaming.
   * <b>Method testVault is supposed to be empty.</b>
   */
  def testVault {
  }

  private var lineconnection: LineConnection = null
}

